name: 'DBS Scraper | Web deploy'

on:
  workflow_dispatch:
    
  push:
    branches:
      - master
    tags:
      - 'cards_**'
    paths:
      - 'web-page/**'
      - '.github/workflows/web-deploy.yml'

jobs:
  deploy:
    name: 'Build & Deploy'
    runs-on: ubuntu-latest
    env:
      LATEST_RELEASE_CARDS_FILE: ./web-page/src/cards.json
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download cards.json from latest release
        uses: Xotl/cool-github-releases@v1
        with:
          assets: cards.json|${{env.LATEST_RELEASE_CARDS_FILE}}
          github_token: ${{ github.token }} 

      - name: Build Docker image
        run: |
          docker build --no-cache -t dbs-web ./web-page
      
      - name: Build app files
        run: |
          docker run --name dbs-container dbs-web npm run build
      
      - name: Extract build files & prepare folder
        run: |
          git rm -rf .
          git clean -fxd
          docker cp dbs-container:/home/node/app/build/. ./
          docker rm dbs-container

      - name: Push to gh-pages branch
        env:
          REMOTE_REPO: https://${{ github.token }}@github.com/${{ github.repository }}.git
        run: |
          NEW_TAG="web_$(date --utc '+%Y-%m-%d/%Hh-%Mm')"
          git config user.name "github"
          git config user.email "noreply@github.com"
          git add -A
          git commit -m "${NEW_TAG} | Auto pushed from Github Actions"
          git tag -a "${NEW_TAG}" -m "${NEW_TAG} | Auto pushed from Github Actions"
          git push -f --follow-tags ${REMOTE_REPO} HEAD:gh-pages
          
      - name: Request Github Pages build job
        run: >-
          curl -L -X POST 
          -H "Content-Type: application/json"
          -H "Authorization: token ${{ secrets.GITHUB_OAUTH_TOKEN }}"
          "https://api.github.com/repos/${{ github.repository }}/pages/builds"
